# Generated by Django 5.0.6 on 2024-07-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link')),
                ('description', models.CharField(max_length=32, verbose_name='Title of a link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
        ),
    ]
