volumes:
  pg_data:
  static:
  media:
  created_config:
  backups:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - backups:/db_backups
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5 
  backend:
    depends_on:
      db:
        condition: service_healthy 

    image: rodypa/django-gallery-backend:production
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/django_gallery/media/
      - created_config:/app/django_gallery/django_gallery/created_config
      - backups:/backend_backups
  gateway:
    depends_on:
      - backend
    image: rodypa/django-gallery-gateway:production
    volumes:
      - static:/staticfiles/
      - media:/app/django_gallery/media/
    ports:
      - 8070:80