# Generated by Django 5.0.6 on 2024-08-12 05:03

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_albumsubcategory'),
        ('images', '0007_alter_photo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='albums.albumsubcategory', verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 12, 5, 3, 18, 23941, tzinfo=datetime.timezone.utc), help_text='The image date can be user defined or extracted from the image if it has appropriate meta data.', null=True, verbose_name='Date of image'),
        ),
    ]
