
FROM python:3.10

RUN pip install --upgrade pip
RUN pip install gunicorn==20.1.0
COPY ./requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY . /app
WORKDIR /app

COPY ./entrypoint_dev.sh .
ENTRYPOINT ["sh", "/app/entrypoint_dev.sh"]