# Generated by Django 5.0.6 on 2024-07-09 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name="Section's title")),
                ('is_the_highest_section', models.BooleanField(default=False, help_text='Determine if this section is the highest. The highest section cannot have parent_section.', verbose_name='Is the highest section')),
                ('parent_section', models.ForeignKey(null=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.SET_NULL, to='albums.section', verbose_name='Parent_Section')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name="Album's title")),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True, verbose_name='Unique title of an album')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_published', models.BooleanField(default=True, help_text='If selected, album will be seen on the site.', verbose_name='Is published')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
