# Generated by Django 5.0.6 on 2024-07-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='albums.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='parent_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daughter_sections', to='albums.section', verbose_name='Parent_Section'),
        ),
    ]
