# Generated by Django 5.0.6 on 2024-07-10 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_section_alter_section_parent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_published',
            field=models.BooleanField(default=True, help_text='If selected, section will be seen on the site.', verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='section',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daughter_sections', to='albums.section', verbose_name='Parent_Section'),
        ),
    ]
