# Generated by Django 5.0.6 on 2024-08-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_options_album_is_in_main_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('year_sorted', 'year sorted')], max_length=128, verbose_name='Title')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='albums.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='album',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='albums.albumtemplate', verbose_name='Template'),
        ),
    ]
