# Generated by Django 5.0.6 on 2024-08-12 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_albumtemplate_alter_album_section_album_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name="Subcategory's title")),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='albums.album', verbose_name='Subcategory')),
            ],
        ),
    ]
