# Generated by Django 5.0.6 on 2024-08-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_albumsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsubcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='albumtemplate',
            name='title',
            field=models.CharField(choices=[('year_sorted', 'year sorted'), ('subdivided', 'subdivided')], max_length=128, verbose_name='Title'),
        ),
    ]
