# Generated by Django 5.0.6 on 2024-08-26 07:16

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_simplealbum_subcategorydividedalbum_yeardividedalbum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumsubcategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'Album Subcategories'},
        ),
        migrations.AddField(
            model_name='album',
            name='show_description',
            field=models.BooleanField(default=True, help_text='If selected, album description will be seen on the site.', verbose_name='Show description'),
        ),
        migrations.AlterField(
            model_name='albumsubcategory',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='albums.album', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='albumsubcategory',
            name='title',
            field=models.CharField(max_length=128, validators=[core.validators.CharFieldValidator], verbose_name="Subcategory's title"),
        ),
    ]
