# Generated by Django 5.0.6 on 2024-09-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_albumsubcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsubcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.CreateModel(
            name='YearDividedAlbumExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_order', models.CharField(choices=[('desc', 'descending'), ('asc', 'ascending')], default='desc', help_text='Determine the order in which the photoswill be displayed on the album page.', max_length=4, verbose_name='year order')),
                ('year_divided_album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to='albums.yeardividedalbum')),
            ],
        ),
    ]
