# Generated by Django 5.0.6 on 2024-09-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_albumsubcategory_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yeardividedalbumextradata',
            old_name='year_divided_album',
            new_name='album',
        ),
    ]
