# Generated by Django 5.0.6 on 2024-09-08 11:40

from django.db import migrations


def create_missing_extra_data(apps, schema_editor):
    YearDividedAlbum = apps.get_model('albums', 'YearDividedAlbum')
    YearDividedAlbumExtraData = apps.get_model('albums', 'YearDividedAlbumExtraData')

    albums = YearDividedAlbum.objects.all()
    for album in albums:
        YearDividedAlbumExtraData.objects.get_or_create(album=album)


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_albumsubcategory_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yeardividedalbumextradata',
            old_name='year_divided_album',
            new_name='album',
        ),
        migrations.RunPython(create_missing_extra_data)
    ]
