name: Deploy Documentation

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinxcontrib_django
        pip install sphinx-rtd-theme 

    - name: Build documentation
      run: |
        cd ./backend/docs
        make html
    
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Debug - List files after build
      run: |
        cd ./backend/docs/_build/html/
        ls -la  # List all files to ensure the output directory is correct

    - name: Copy files using custom SCP command
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.DOCUMENTATION_HOST }}
        username: ${{ secrets.DOCUMENTATION_HOST_USER }}
        key: ${{ secrets.DOCUMENTATION_SSH_KEY }}
        port: 22
        script: |
          scp -r ./backend/docs/_build/html/* ${{ secrets.DOCUMENTATION_HOST_USER }}@${{ secrets.DOCUMENTATION_HOST }}:~/projects-documentations/django-gallery/

